[package]
edition.workspace = true
license.workspace = true
name = "env"
publish.workspace = true
version.workspace = true

[dependencies]
dotenv.workspace = true
eyre.workspace = true
rand.workspace = true
tracing.workspace = true
