[package]
name = "bot-client-couch"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
bincode.workspace = true
bot-core.workspace = true
bot-client-trainings.workspace = true
bot-viewer.workspace = true
chrono.workspace = true
eyre.workspace = true
futures-util.workspace = true
hex.workspace = true
itertools.workspace = true
mongodb.workspace = true
rights.workspace = true
serde.workspace = true
strum.workspace = true
teloxide.workspace = true
tracing.workspace = true
trainings.workspace = true
users.workspace = true
