[package]
name = "ident"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
time.workspace = true
bson.workspace = true
serde.workspace = true
