[package]
name = "users"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
bson.workspace = true
chrono.workspace = true
serde.workspace = true
eyre.workspace = true
decimal.workspace = true

