[package]
edition.workspace = true
license.workspace = true
name = "stat"
publish.workspace = true
version.workspace = true

[dependencies]
decimal.workspace = true
model.workspace = true
ledger.workspace = true
ai.workspace = true

chrono.workspace = true
eyre.workspace = true