name: sf
description: "SF Web App"
publish_to: "none"
version: 0.1.3

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  grpc: ^4.0.4
  protobuf: ^4.1.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  protoc_plugin: ^22.3.0

flutter:
  uses-material-design: true
