[package]
name = "trainings"

edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
bson.workspace = true
eyre.workspace = true
chrono.workspace = true
thiserror.workspace = true
mongodb.workspace = true
